# Site wide configuration
#---------------------------

title: Zero Waste Festival
description: "Zero Waste Festival Ireland is a community-led innitiative to bring Zero Waste awareness to Ireland through a series of pop-up festival all over the country."

url: https://www.zerowastefestival.ie
baseurl: ""

locale: en

logo: logo-square-120.png # 120x120 px default image used for Twitter summary card
teaser: zero-waste-blank-400x250.png # 400x250 px default teaser image used in image archive grid

# Author info under posts
#---------------------------

owner:
  name: Zero Waste Festival Ireland 
  email: info@zerowastefestival.ie
  twitter: ZeroWasteFest
  bio: We are a community-run initiative to facilitate zero waste networking, learning, and sharing in Ireland through a series on pop-up festivals including workshops, talks, screenings, and meet-up sessions at various locations.
  avatar: logo-square-160.png # 160x160 px image for author byline

# Jekyll configuration
#---------------------------

kramdown:
  toc_levels: 1..2
highlighter: rouge

permalink: /:categories/:title/
include: ['_pages']

feed:
  path: feed.xml

sass:
  sass_dir: _sass
  style: compressed
  
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
